fix RHOAIENG-67943
Signed-off-by: Nelesh Singla <117123879+nsingla@users.noreply.github.com>

diff --git a/.github/workflows/build-prs.yml b/.github/workflows/build-prs.yml
--- a/.github/workflows/build-prs.yml
+++ b/.github/workflows/build-prs.yml
@@ -7,8 +7,6 @@ on:
 env:
   IMAGE_REPO_DSPO: data-science-pipelines-operator
   QUAY_ORG: opendatahub
-  QUAY_ID: ${{ secrets.QUAY_ID }}
-  QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
   GH_USER_EMAIL: 140449482+dsp-developers@users.noreply.github.com
   GH_USER_NAME: dsp-developers
 jobs:
@@ -52,6 +50,24 @@ jobs:
           pr_state=$(cat ./pr_state)
           head_sha=$(cat ./head_sha)
           event_action=$(cat ./event_action)
+
+          if [[ ! "$pr_number" =~ ^[0-9]+$ ]]; then
+            echo "::error::Invalid PR Number: must be numeric"
+            exit 1
+          fi
+          if [[ ! "$pr_state" =~ ^(open|closed)$ ]]; then
+            echo "::error::Invalid PR State: must be 'open' or 'closed'"
+            exit 1
+          fi
+          if [[ ! "$head_sha" =~ ^[0-9a-f]{40}$ ]]; then
+            echo "::error::Invalid head_sha: must be a 40-character hex SHA"
+            exit 1
+          fi
+          if [[ ! "$event_action" =~ ^(opened|reopened|closed|synchronize)$ ]]; then
+            echo "::error::Invalid Event Action: unexpected value"
+            exit 1
+          fi
+
           echo "pr_number=${pr_number}" >> $GITHUB_OUTPUT
           echo "pr_state=${pr_state}" >> $GITHUB_OUTPUT
           echo "head_sha=${head_sha}" >> $GITHUB_OUTPUT
@@ -71,6 +87,9 @@ jobs:
       - uses: actions/checkout@v3
       - name: Build Image
         uses: ./.github/actions/build
+        env:
+          QUAY_ID: ${{ secrets.QUAY_ID }}
+          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
         with:
           OVERWRITE: true
           IMAGE_REPO: ${{ env.IMAGE_REPO_DSPO }}
@@ -91,46 +110,43 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
           IMG: quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_REPO_DSPO }}:${{ env.TARGET_IMAGE_TAG }}
+          EVENT_ACTION: ${{ needs.fetch-data.outputs.event_action }}
+          PR_NUMBER: ${{ needs.fetch-data.outputs.pr_number }}
+          PR_SOURCE_BRANCH: ${{ needs.fetch-data.outputs.head_sha }}
         run: |
           git config user.email "${{ env.GH_USER_EMAIL }}"
           git config user.name "${{ env.GH_USER_NAME }}"
 
-          action=${{ needs.fetch-data.outputs.event_action }}
-
-          if [[ "$action" == "synchronize" ]]; then
+          if [[ "$EVENT_ACTION" == "synchronize" ]]; then
             echo "Change to PR detected. A new PR build was completed." >> /tmp/body-file.txt
           fi
 
-          if [[ "$action" == "reopened" ]]; then
+          if [[ "$EVENT_ACTION" == "reopened" ]]; then
             echo "PR was re-opened." >> /tmp/body-file.txt
           fi
 
-          cat <<"EOF" >> /tmp/body-file.txt
-            A new image has been built to help with testing out this PR: `${{ env.IMG }}`
-          EOF
+          echo "A new image has been built to help with testing out this PR: \`${IMG}\`" >> /tmp/body-file.txt
 
-          if [[ "$action" == "opened" || "$action" == "reopened" ]]; then
-          cat <<"EOF" >> /tmp/body-file.txt
-          An OCP cluster where you are logged in as cluster admin is required.
-
-          To use this image run the following:
-
-          ```bash
-          cd $(mktemp -d)
-          git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
-          cd data-science-pipelines-operator/
-          git fetch origin pull/${{ needs.fetch-data.outputs.pr_number }}/head
-          git checkout -b pullrequest ${{ env.SOURCE_BRANCH }}
-          oc new-project opendatahub
-          make deploy IMG="${{ env.IMG }}"
-          ```
-
-          More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.
-
-          EOF
+          if [[ "$EVENT_ACTION" == "opened" || "$EVENT_ACTION" == "reopened" ]]; then
+            echo "" >> /tmp/body-file.txt
+            echo "An OCP cluster where you are logged in as cluster admin is required." >> /tmp/body-file.txt
+            echo "" >> /tmp/body-file.txt
+            echo "To use this image run the following:" >> /tmp/body-file.txt
+            echo "" >> /tmp/body-file.txt
+            echo '```bash' >> /tmp/body-file.txt
+            echo 'cd $(mktemp -d)' >> /tmp/body-file.txt
+            echo 'git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git' >> /tmp/body-file.txt
+            echo 'cd data-science-pipelines-operator/' >> /tmp/body-file.txt
+            echo "git fetch origin pull/${PR_NUMBER}/head" >> /tmp/body-file.txt
+            echo "git checkout -b pullrequest ${PR_SOURCE_BRANCH}" >> /tmp/body-file.txt
+            echo 'oc new-project opendatahub' >> /tmp/body-file.txt
+            echo "make deploy IMG=\"${IMG}\"" >> /tmp/body-file.txt
+            echo '```' >> /tmp/body-file.txt
+            echo "" >> /tmp/body-file.txt
+            echo "More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application." >> /tmp/body-file.txt
           fi
 
-          gh pr comment ${{ needs.fetch-data.outputs.pr_number }} --body-file /tmp/body-file.txt
+          gh pr comment "${PR_NUMBER}" --body-file /tmp/body-file.txt
 
   clean-pr-images:
     if: needs.fetch-data.outputs.pr_state == 'closed'
@@ -144,13 +160,16 @@ jobs:
     steps:
       - name: Delete PR image
         shell: bash
+        env:
+          QUAY_ID: ${{ secrets.QUAY_ID }}
+          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
         run: |
           tag=$(curl --request GET 'https://quay.io/api/v1/repository/${{ env.QUAY_ORG }}/${{ env.IMAGE_REPO_DSPO }}/tag/?specificTag=${{ env.TARGET_IMAGE_TAG }}')
           exists=$(echo ${tag} | yq .tags - | yq any)
           IMAGE=quay.io/${{ env.QUAY_ORG }}/${{ env.IMAGE_REPO_DSPO }}:${{ env.TARGET_IMAGE_TAG }}
           if [[ "$exists" == "true" ]]; then
-            echo "PR Closed deleting image...${{ env.IMAGE }}."
-            skopeo delete --creds ${{ env.QUAY_ID }}:${{ env.QUAY_TOKEN }} docker://${IMAGE}
+            echo "PR Closed deleting image...${IMAGE}."
+            skopeo delete --creds "${QUAY_ID}:${QUAY_TOKEN}" docker://${IMAGE}
           else
             echo "Deletion of image ${IMAGE} skipped because image already does not exist."
           fi
